### ISSUE TITLE
Remove peerDependencies

### ISSUE THREAD

**Issue by zenorocha** [eduardolundgren/dotfiles#55]
There's been a lot of discussion about removing `peerDependencies` https://github.com/npm/npm/issues/5080, which has caused a lot of trouble when trying to update stuff in Node.

Should we remove too?

**Comment by paulohp** [comment]
I think so, everytime that I try to update the dotfiles I have problems with `peerDependencies`.

You got my :+1:

**Comment by eduardolundgren** [comment]
Fixed on v0.8.0.
